<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cards')->delete();
        
        \DB::table('cards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '{"en":"Info","ru":"Инфо"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:07:36',
                'updated_at' => '2022-11-08 17:40:42',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '{"en":"Quest"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:33:42',
                'updated_at' => '2022-11-10 23:33:42',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '{"en":"Event","ru":"Событие"}',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-09 04:51:54',
                'updated_at' => '2022-11-10 01:49:48',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '{"ru":"Место","en":"Place"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:56:32',
                'updated_at' => '2022-11-08 17:40:21',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '{"en":"Creature","ru":"Существо"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:11:58',
                'updated_at' => '2022-11-08 17:40:54',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '{"en":"Item"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:57:58',
                'updated_at' => '2022-11-10 23:57:58',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '{"en":"Power","ru":"Сила"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:43:27',
                'updated_at' => '2022-11-11 00:09:25',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '{"en":"Legend","ru":"Легенда"}',
                'desc' => '{"en":"A people without legends is like a tree without roots."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 1,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:07:52',
                'updated_at' => '2022-11-08 17:42:46',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '{"en":"Clan","ru":"Клан"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 1,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:08:04',
                'updated_at' => '2022-11-11 00:08:20',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => '{"en":"Practice"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:36:58',
                'updated_at' => '2022-11-10 14:36:58',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => '{"en":"Find"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:39:42',
                'updated_at' => '2022-11-10 14:39:42',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => '{"en":"Encounter","ru":"Встреча"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-09 04:55:16',
                'updated_at' => '2022-11-11 00:07:30',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => '{"en":"Wilderness"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 4,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:24:51',
                'updated_at' => '2022-11-10 14:24:51',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => '{"en":"Settlement"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 4,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:26:20',
                'updated_at' => '2022-11-10 14:26:20',
            ),
            14 => 
            array (
                'id' => 19,
                'name' => '{"en":"Animal","ru":"Животное"}',
                'desc' => '{"en":"This world is replete with an unimaginable variety of animals."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:13:44',
                'updated_at' => '2022-11-08 17:43:10',
            ),
            15 => 
            array (
                'id' => 20,
                'name' => '{"en":"Plant","ru":"Растение"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:14:35',
                'updated_at' => '2022-11-08 17:43:38',
            ),
            16 => 
            array (
                'id' => 21,
                'name' => '{"en":"Human","ru":"Человек"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:15:03',
                'updated_at' => '2022-11-08 17:44:02',
            ),
            17 => 
            array (
                'id' => 22,
                'name' => '{"en":"Enemy"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:49:41',
                'updated_at' => '2022-11-12 03:49:41',
            ),
            18 => 
            array (
                'id' => 27,
                'name' => '{"en":"Spirit","ru":"Дух"}',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 7,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:43:41',
                'updated_at' => '2022-11-08 02:44:22',
            ),
            19 => 
            array (
                'id' => 28,
                'name' => '{"en":"Mountain"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 01:57:20',
                'updated_at' => '2022-11-12 01:57:20',
            ),
            20 => 
            array (
                'id' => 29,
                'name' => '{"en":"Grassland"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:02:37',
                'updated_at' => '2022-11-12 03:02:37',
            ),
            21 => 
            array (
                'id' => 30,
                'name' => '{"en":"Seasonal Forest"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:04:11',
                'updated_at' => '2022-11-12 03:04:11',
            ),
            22 => 
            array (
                'id' => 31,
                'name' => '{"en":"Savanna"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:09:23',
                'updated_at' => '2022-11-12 03:09:23',
            ),
            23 => 
            array (
                'id' => 32,
                'name' => '{"en":"Lake"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:24:41',
                'updated_at' => '2022-11-12 03:25:24',
            ),
            24 => 
            array (
                'id' => 33,
                'name' => '{"en":"River"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:25:49',
                'updated_at' => '2022-11-12 03:26:03',
            ),
            25 => 
            array (
                'id' => 34,
                'name' => '{"en":"Swamp"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:27:08',
                'updated_at' => '2022-11-12 03:27:08',
            ),
            26 => 
            array (
                'id' => 35,
                'name' => '{"ru":"Джунгли","en":"Rainforest"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:56:49',
                'updated_at' => '2022-11-12 04:02:21',
            ),
            27 => 
            array (
                'id' => 36,
                'name' => '{"en":"Lanza Piya"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 15,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:31:06',
                'updated_at' => '2022-11-10 14:31:06',
            ),
            28 => 
            array (
                'id' => 37,
                'name' => '{"en":"Hero"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:33:23',
                'updated_at' => '2022-11-10 23:33:23',
            ),
            29 => 
            array (
                'id' => 38,
                'name' => '{"en":"Eagle Nest","ru":"Орлиное Гнездо"}',
                'desc' => '{"en":"This ancient clan still lives in the depths of the unknown to this day. Finding the way to the inconspicuous is easy. But everyone who follows his own path of the heart will certainly meet him.","ru":"Этот древний клан и по сей день живет в самых недрах неизведанного. Найти дорогу к нему не просто. Но каждый, кто следует своему пути сердца однажды непременно встречается с ним"}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 1,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:16:54',
                'updated_at' => '2022-11-09 04:42:58',
            ),
            30 => 
            array (
                'id' => 39,
                'name' => '{"en":"Serpent Path","ru":"Тропа Змея"}',
                'desc' => '{"en":"The wise people follow the sacred path of the Serpent. Everyone who walks this path cultivates living blood in himself. Everyone who walks this path holds on to the other in order to honor this path together.","ru":"Мудрый народ следует священной Тропе Змея. Каждый, идущий по этой тропе, взращивает в себе кровь живую. Каждый, идущий по этой тропе, держится другого чтобы вместе чтить этот путь."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 1,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:09:50',
                'updated_at' => '2022-11-09 04:43:14',
            ),
            31 => 
            array (
                'id' => 40,
                'name' => '{"en":"Totem Quest"}',
                'desc' => '{"en":"To pass the initiation ceremony, Titu needs to find his totem of power. The difficulty is that the boy so far has a rather poor understanding of what it is and where to look for it.\\r\\n\\r\\nTherefore, at every opportunity, he needs to extract any information on this topic."}',
                'is_public' => false,
                'image' => 'ym4kFiMwWuKnM1KfNx7ZsM1GgigRPVAaqZkeAx63.jpg',
                'scope_id' => 2,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:41:18',
                'updated_at' => '2022-11-10 23:41:18',
            ),
            32 => 
            array (
                'id' => 17,
                'name' => '{"en":"Bird","ru":"Птица"}',
                'desc' => '{"en":"Birds are a group of warm-blooded vertebrates, characterized by feathers, toothless beaked jaws, the laying of hard-shelled eggs, a high metabolic rate, a four-chambered heart, and a strong yet lightweight skeleton. Birds live worldwide and range in size from the bee hummingbird to the ostrich. There are about ten thousand living species, more than half of which are passerine, or \\"perching\\" birds.\\r\\n\\r\\nMany social species pass on knowledge across generations, which is considered a form of culture. Birds are social, communicating with visual signals, calls, and songs, and participating in such behaviours as cooperative breeding and hunting, flocking, and mobbing of predators."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:17:34',
                'updated_at' => '2022-11-13 02:30:53',
            ),
            33 => 
            array (
                'id' => 42,
                'name' => '{"en":"Knowledge"}',
                'desc' => '{"en":"Nothing is free in this world, and the acquisition of knowledge is the most difficult of all tasks that a person can face."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 7,
                'owner_id' => 1,
                'created_at' => '2022-11-10 15:40:03',
                'updated_at' => '2022-11-10 15:40:03',
            ),
            34 => 
            array (
                'id' => 43,
                'name' => '{"en":"Airi","ru":"Айри"}',
                'desc' => '{"en":"Many tribes of the Rainforest believe in the existence of a powerful and wise spirit who is the guardian and protector of the jungle, as well as all its inhabitants.","ru":"Многие племена Тропического Леса верят в существование могущественного и мудрого духа, который является хранителем и защитником джунглей, а также всех его обитателей."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:35:19',
                'updated_at' => '2022-11-09 04:41:22',
            ),
            35 => 
            array (
                'id' => 10,
                'name' => '{"en":"Weariness"}',
                'desc' => '{"en":"Even the heroes get tired over time. And the more weariness they accumulate, the harder it is for them to act. Weariness is removed by rest and food."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:36:47',
                'updated_at' => '2022-11-15 17:50:25',
            ),
            36 => 
            array (
                'id' => 25,
                'name' => '{"en":"Herbivore"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 64,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:58:18',
                'updated_at' => '2022-11-16 02:22:54',
            ),
            37 => 
            array (
                'id' => 26,
                'name' => '{"en":"Frugivorous"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 64,
                'owner_id' => 1,
                'created_at' => '2022-11-12 04:23:13',
                'updated_at' => '2022-11-16 02:23:18',
            ),
            38 => 
            array (
                'id' => 24,
                'name' => '{"en":"Predator"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 64,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:54:28',
                'updated_at' => '2022-11-16 02:23:47',
            ),
            39 => 
            array (
                'id' => 44,
                'name' => '{"en":"Shiinhaku","ru":"Шиинхаку"}',
                'desc' => '{"en":"From time immemorial, the various tribes of the Rainforest have legends about this insidious and evil spirit.","ru":"С незапамятных времен у различных племен Тропического Леса ходят легенды об этом коварном и злобном духе."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:34:07',
                'updated_at' => '2022-11-09 04:41:35',
            ),
            40 => 
            array (
                'id' => 45,
                'name' => '{"en":"Pua","ru":"Пуа"}',
                'desc' => '{"en":"Perhaps this is the most educated boy in the entire settlement. From an early age, he showed great interest in the legends and knowledge of his tribe. This is one of the few guys who can read and write well and loves to do it.\\r\\n\\r\\nMany, not without reason, believe that the old keeper is preparing this boy to replace him.","ru":"Пожалуй, это самый образованный мальчик во всем поселении. С малых лет он проявил большой интерес к легендам и знаниям своего племени. Это один из немногих ребят, кто умеет хорошо читать и писать и любит этим заниматься.\\r\\n\\r\\nМногие не без оснований считают, что старый хранитель готовит этого мальчика себе на смену."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:33:05',
                'updated_at' => '2022-11-09 04:41:47',
            ),
            41 => 
            array (
                'id' => 46,
                'name' => '{"en":"Araki","ru":"Араки"}',
                'desc' => '{"en":"This is a bright and noisy toucan, the favorite pet of Rekko, Titu\'s father.","ru":"Это яркий и шумный тукан, любимый питомец Рекко, отца Титу."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:29:38',
                'updated_at' => '2022-11-09 04:42:13',
            ),
            42 => 
            array (
                'id' => 47,
                'name' => '{"en":"Lilika","ru":"Лилика"}',
                'desc' => '{"en":"Although this young lady was nicknamed Beauty in the settlement, it should be noted that this is by no means her only virtue. Everyone is well aware of her talents for healing, especially after she began to help many of her tribe.\\r\\n\\r\\nIn addition, Lilika has always been distinguished by unprecedented seriousness and diligence in the study of plants and various healing agents. By her childhood years, she had already managed to accumulate considerable knowledge and skills in these areas.","ru":"Хотя эту молодую особу и прозвали в поселении Красавицей, нужно отметить что это вовсе не единственное ее достоинство. Всем хорошо известны ее таланты к целительству, особенно после того как она начала помогать многим из своего племени. \\r\\n\\r\\nКроме того, Лилика всегда отличалась небывалой серьезностью и старательностью в изучении растений и различных целебных средств. К своим детским годам она уже успела накопить немалые знания и навыки в этих сферах."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:36:25',
                'updated_at' => '2022-11-09 04:41:07',
            ),
            43 => 
            array (
                'id' => 48,
                'name' => '{"en":"Zaizi","ru":"Зайзи"}',
                'desc' => '{"en":"This boy, like all other children in his village, was brought up not only by his parents but by the whole tribe. He has a sharp mind and sparkling humor. Loves to joke and make fun. Regularly plunges into various stories. He has a great talent for singing and artistic performances. Careless and careless.\\r\\n\\r\\nLike all his peers, Zaizi will soon have to go through his initiation ceremony. However, the boy does not think about it at all, because he is worried about completely different questions, let\'s say ... of a cordial nature ...\\r\\n\\r\\nFrom an early age, he leads a strong friendship with his peer Titu, with whom they spend a lot of time organizing all sorts of tricks.","ru":"Этот мальчик, как и все прочие дети в его поселке, воспитывался не только своими родителями, но и всем племенем. Обладает острым умом и искрометным юмором. Обожает шутить и подшучивать. Регулярно вляпывается в различные истории. Имеет большой талант к пению и артистическим выступлениям. Беспечен и легкомысленен.\\r\\n\\r\\nКак и всем его сверстникам, вскоре Зайзи предстоит пройти свою церемонию инициации. Впрочем, мальчик совсем не думает об этом, поскольку его беспокоят совершенно другие вопросы, скажем так... сердечного характера...\\r\\n\\r\\nС малых лет ведет крепкую дружбу со своим сверстником Титу, с которым они проводят много времени, организуя всяческие проделки."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:31:41',
                'updated_at' => '2022-11-09 04:42:00',
            ),
            44 => 
            array (
                'id' => 50,
                'name' => '{"en":"Blue Morpho Butterfly"}',
                'desc' => '{"en":"With its brilliant, iridescent blue wings, the blue morpho butterfly flutters through the rainforest canopy. The many “eyespots” on its brown underside trick predators into thinking the butterfly is a large predator.\\r\\n\\r\\nThe blue morpho’s diet changes throughout each stage of its lifecycle. As a caterpillar, it chews leaves of many varieties but prefers to dine on plants in the pea family. When it becomes a butterfly it can no longer chew, but drinks its food instead. Adults use a long, protruding mouthpart called a proboscis as a drinking straw to sip the juice of rotting fruit, the fluids of decomposing animals, tree sap, fungi, and wet mud. Blue morphos taste fruit with sensors on their legs, and they “taste-smell” the air with their antennae, which serve as a combined tongue and nose.\\r\\n\\r\\nBirds like the jacamar and flycatcher are the adult butterfly’s natural predators."}',
                'is_public' => false,
                'image' => '4a5tCKCnyZjFIwKK8UUexarCh3Vs9cYVYnJZDm8y.jpg',
                'scope_id' => 18,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:19:01',
                'updated_at' => '2022-11-12 02:25:04',
            ),
            45 => 
            array (
                'id' => 52,
                'name' => '{"en":"Brown Sloth"}',
                'desc' => '{"en":"This cat-sized mammal, typically weighing 8 – 9 pounds, has a round head, a short snout, small eyes, long legs, tiny ears, and a stubby tail. Sloths have long, coarse fur that is light brown in color but often appears green due to the blue-green algae that grow there. Instead of toes, their front and hind feet have three curved claws that allow them to easily hook onto tree branches and hang upside-down. Sloths can rotate their heads nearly 90 degrees, and their mouths are shaped so they look like they are always smiling.\\r\\n\\r\\nTheir algae-covered fur helps camouflage the sloth in its forest environment. Sloths spend nearly all of their time in trees, descending to the ground only once a week to defecate.\\r\\n\\r\\nSloths are among the slowest-moving animals on Earth; they can swim but are virtually unable to walk. This makes them an easy target for jaguars, eagles, and people that hunt sloths for their meat."}',
                'is_public' => false,
                'image' => 'Ia6saaiCLY490Tzug5xoc69if21dYC0HOBf62OQH.jpg',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:48:34',
                'updated_at' => '2022-11-12 02:49:41',
            ),
            46 => 
            array (
                'id' => 41,
                'name' => '{"en":"Travel"}',
                'desc' => '{"en":"Something always happens along the way..."}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 60,
                'owner_id' => 1,
                'created_at' => '2022-11-10 13:55:09',
                'updated_at' => '2022-11-15 17:04:39',
            ),
            47 => 
            array (
                'id' => 54,
                'name' => '{"en":"Mountain Gorilla"}',
                'desc' => '{"en":"Mountain gorillas are the largest living primates on earth! They can move on their two feet, on all four of their limbs, and can also climb trees and even swing from branches. Mountain gorillas, along with chimpanzees, orangutans, and bonobos, are the closest living relatives of humans, with mountain gorillas having the most developed brain of the four.\\r\\n\\r\\nMountain gorillas live in groups of roughly 30, with one dominant, male troop leader called a ‘silverback’ for the silver tint in his coat. The dominant silverback is in charge of coordinating when the troop eats, rests, and moves around the group’s home range, and the rest of the group is organized in a complex, evolved social order that points to the mountain gorilla’s extraordinary intelligence.\\r\\n\\r\\nMountain gorillas are primarily herbivores and they eat large portions of over 100 different kinds of plants. They do not drink much water because they get most of their needed hydration from their constant consumption of plants."}',
                'is_public' => false,
                'image' => 'l3y3Rr27v9fHC8Up2ojegcx2YdmkpJ5OoBy56k03.jpg',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-12 01:35:45',
                'updated_at' => '2022-11-12 04:13:27',
            ),
            48 => 
            array (
                'id' => 53,
                'name' => '{"en":"Capybara"}',
                'desc' => '{"en":"Capybaras are the largest rodents on earth. They have a heavy, barrel-shaped body that sits on relatively squat legs, shorter in the front than the back. Their brown fur is coarse and sparse enough to reveal the grey skin beneath it.\\r\\n\\r\\nFeeding mostly in the afternoon, and on and off at night, capybaras tend to doze in the morning. They take short naps throughout the day while other members of their group stand guard.\\r\\n\\r\\nThey are herbivores and eat the vegetation that lines water sources and other aquatic plants. They also eat their own poop, which contains beneficial bacteria that helps their stomach to break down the fiber from the grass. During the dry season or in drought conditions, capybaras will also eat grains, melons, reeds and squashes."}',
                'is_public' => false,
                'image' => '4TGnMBEBJrTHKhjJurd7rupbVf30jnagpJlECi4j.png',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:22:02',
                'updated_at' => '2022-11-13 02:56:18',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => '{"en":"Jaguar"}',
                'desc' => '{"en":"Jaguars spend much of their time on the ground. They use their padded paws to move silently through the forest floor. Although not quite as agile as a leopard, jaguars are capable of climbing trees to hunt or to rest. Jaguars are mostly nocturnal hunters. They use their excellent vision and sharp teeth to ambush prey and crush their skulls."}',
                'is_public' => false,
                'image' => 'p4T9QxXKlY5BR2p0Y75BV7RLy5qCiBGcIUFD8VpC.jpg',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:59:15',
                'updated_at' => '2022-11-13 03:02:50',
            ),
            50 => 
            array (
                'id' => 56,
                'name' => '{"en":"Poison Dart Frog"}',
                'desc' => '{"en":"Poison dart frogs are one of the planet’s most brightly colored animals. Depending on the species, they can be yellow, copper, gold, red, blue, green, black, or a combination of those colors. Their showy colors and startling designs help warn predators of the danger they impose. Within their skin, they store natural venom that can paralyze, or even kill, a predator.\\r\\n\\r\\nThis family of frogs includes some of the world’s most toxic species. The golden poison dart frog, for example, contains enough poison to kill 10 adult men. Indigenous cultures have used these frogs’ poison for centuries to coat the tip of their blow darts before hunting—a tradition that inspired the frogs’ common name.\\r\\n\\r\\nUnlike many other amphibians, poison dart frogs are diurnal. Most species are terrestrial but a few are arboreal. Poison dart frogs are insectivores, preferring to eat ants and other small insects that they can hunt among the leaf litter of the forest floor.\\r\\n\\r\\nMany species of poison dart frogs are very attentive parents. Often these parents choose the tiny pools of water held within bromeliads, and deposit a few tadpoles in each pool."}',
                'is_public' => false,
                'image' => 'L7gvQLME8zT6y50biZuSIRMCmNIwM1U87tsVms3i.webp',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:22:08',
                'updated_at' => '2022-11-13 01:53:19',
            ),
            51 => 
            array (
                'id' => 57,
                'name' => '{"en":"Time"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:55:13',
                'updated_at' => '2022-11-13 01:55:13',
            ),
            52 => 
            array (
                'id' => 58,
                'name' => '{"en":"Day"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 57,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:55:41',
                'updated_at' => '2022-11-13 01:55:41',
            ),
            53 => 
            array (
                'id' => 59,
                'name' => '{"en":"Night"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 57,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:56:02',
                'updated_at' => '2022-11-13 01:56:02',
            ),
            54 => 
            array (
                'id' => 60,
                'name' => '{"en":"Action"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:02:13',
                'updated_at' => '2022-11-13 02:02:13',
            ),
            55 => 
            array (
                'id' => 62,
                'name' => '{"en":"Wetland"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 14,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:24:58',
                'updated_at' => '2022-11-13 02:24:58',
            ),
            56 => 
            array (
                'id' => 63,
                'name' => '{"en":"Habitat"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:29:27',
                'updated_at' => '2022-11-13 02:29:27',
            ),
            57 => 
            array (
                'id' => 18,
                'name' => '{"en":"Insect","ru":"Насекомое"}',
                'desc' => '{"en":"Insects are the most diverse group of animals; they include more than a million described species and represent more than half of all known living organisms. The total number of extant species is estimated at between six and ten million; potentially over 90% of the animal life forms on Earth are insects.\\r\\n\\r\\nInsect pollinators are essential to the life cycle of many flowering plant species on which most organisms, including humans, are at least partly dependent; without them, the terrestrial portion of the biosphere would be devastated. Many insects are considered ecologically beneficial as predators and a few provide direct economic benefit. Silkworms produce silk and honey bees produce honey and both have been domesticated by humans. Insects are consumed as food in 80% of the world\'s nations, by people in roughly 3000 ethnic groups"}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:18:53',
                'updated_at' => '2022-11-13 02:30:20',
            ),
            58 => 
            array (
                'id' => 64,
                'name' => '{"en":"Diet"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:32:11',
                'updated_at' => '2022-11-13 02:32:11',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => '{"en":"Green Anaconda"}',
                'desc' => '{"en":"One of the largest snakes in the world, the green anaconda can reach impressive proportions — over 9 meters in length,  and more than 250 kg! Unlike many animals, female anacondas are considerably larger than their male counterparts. Green anacondas are dark olive-brown with large alternating black spots running down their backs and smaller oval spots with yellow centers along their sides. Their eyes and noses are perched on top of their large heads, allowing them to breathe and see their prey even when submerged in water. Green anacondas are members of the boa family and are non-venomous snakes. They use their teeth and powerful jaws to hold onto their prey while their extremely muscular bodies wrap around their catches to suffocate them or drag them underwater."}',
                'is_public' => false,
                'image' => 'pbYi6xvyfol4ibQ7tMGuwD5RbpPRpWRHGgGhYwi0.jpg',
                'scope_id' => 66,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:21:46',
                'updated_at' => '2022-11-13 02:51:02',
            ),
            60 => 
            array (
                'id' => 65,
                'name' => '{"en":"Reptile"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:48:48',
                'updated_at' => '2022-11-13 02:48:48',
            ),
            61 => 
            array (
                'id' => 66,
                'name' => '{"en":"Snake"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 65,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:49:38',
                'updated_at' => '2022-11-13 02:49:38',
            ),
            62 => 
            array (
                'id' => 67,
                'name' => '{"en":"Evening"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 57,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:53:18',
                'updated_at' => '2022-11-13 02:53:18',
            ),
            63 => 
            array (
                'id' => 68,
                'name' => '{"en":"Morning"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 57,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:54:10',
                'updated_at' => '2022-11-13 02:54:10',
            ),
            64 => 
            array (
                'id' => 49,
                'name' => '{"en":"Scarlet Macaw"}',
                'desc' => '{"en":"Macaws are the largest parrots in the world! This beautiful macaw has a creamy white, almost featherless face, with bright red plumage covering most of its body, wings, and long tail. Brilliant blue and yellow feathers also adorn the lower wings. The bird’s strong beak is adapted to breaking hard nuts found in the rainforest.\\r\\n\\r\\nMacaws also mate for life, nesting from January through April in the holes of dead canopy trees. Mated adults lay up to two eggs per year, and preen each other and their offspring for hours, cleaning bugs from their feathers.\\r\\n\\r\\nNuts, leaves, berries and seeds from the rainforest make up the bulk of the scarlet macaw’s diet. Its strong, hooked beak is perfect for breaking nuts and seeds. Interestingly, the scarlet macaw can eat fruits toxic enough to kill other animals. This could be because they also eat large amounts of clay, which is thought to neutralize plant poisons."}',
                'is_public' => false,
                'image' => 'Jq108MbkcrlwQTFDsW2oJiGoTkOdXIRPIlh6FxwD.jpg',
                'scope_id' => 17,
                'owner_id' => 1,
                'created_at' => '2022-11-12 04:20:48',
                'updated_at' => '2022-11-13 03:16:18',
            ),
            65 => 
            array (
                'id' => 69,
                'name' => '{"en":"Armadillo"}',
            'desc' => '{"en":"Armadillos are characterized by a leathery armor shell and long, sharp claws for digging. They have short legs but can move quite quickly. When threatened by a predator, Tolypeutes species frequently roll up into a ball; they are the only species of armadillo capable of this.\\r\\n\\r\\nThe diets of different armadillo species vary but consist mainly of insects, grubs, and other invertebrates. Some species, however, feed almost entirely on ants and termites.\\r\\n\\r\\nThey are prolific diggers. Many species use their sharp claws to dig for food, such as grubs, and to dig dens. The nine-banded armadillo prefers to build burrows in moist soil near the creeks, streams, and arroyos around which it lives and feeds.\\r\\n\\r\\nArmadillos have very poor eyesight and use their keen sense of smell to hunt for food. They use their claws for digging and finding food, as well as for making their homes in burrows. They dig their burrows with their claws, making only a single a corridor the width of the animal\'s body.\\r\\n\\r\\nThe underside of the animal is never armored and is simply covered with soft skin and fur. This armor-like skin appears to be an important defense for many armadillos, although most escape predators by fleeing (often into thorny patches, from which their armor protects them) or digging to safety. Only the South American three-banded armadillos (Tolypeutes) rely heavily on their armor for protection.\\r\\n\\r\\nArmadillos have short legs but can move quite quickly. The nine-banded armadillo is noted for its movement through water which is accomplished via two different methods: it can walk underwater for short distances, holding its breath for as long as six minutes; also, crossing larger bodies of water, it is capable of increasing its buoyancy by swallowing air, inflating its stomach and intestines"}',
                'is_public' => false,
                'image' => 'Ta4I5x2IUdeCpROws65OtvObVKa47eeUMXVdASXK.jpg',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-13 18:04:42',
                'updated_at' => '2022-11-13 18:05:06',
            ),
            66 => 
            array (
                'id' => 70,
                'name' => '{"en":"Nothing"}',
                'desc' => '{"en":"The meaning of this card depends on the context."}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:09:47',
                'updated_at' => '2022-11-15 17:09:47',
            ),
            67 => 
            array (
                'id' => 71,
                'name' => '{"en":"Success"}',
                'desc' => '{"en":"The meaning of this card depends on the context."}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:11:37',
                'updated_at' => '2022-11-15 17:11:37',
            ),
            68 => 
            array (
                'id' => 72,
                'name' => '{"en":"Fail"}',
                'desc' => '{"en":"The meaning of this card depends on the context."}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => NULL,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:12:25',
                'updated_at' => '2022-11-15 17:12:47',
            ),
            69 => 
            array (
                'id' => 74,
                'name' => '{"en":"Flashback"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:26:20',
                'updated_at' => '2022-11-15 17:26:20',
            ),
            70 => 
            array (
                'id' => 73,
                'name' => '{"en":"Damage"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 3,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:16:42',
                'updated_at' => '2022-11-15 17:45:32',
            ),
            71 => 
            array (
                'id' => 16,
                'name' => '{"en":"Character","ru":"Персонаж"}',
                'desc' => '{"en":"Any creature that plays an important role in this book is a character. Each character has a name, skills, knowledge, features, and other characteristics.\\r\\n\\r\\nAlso, each character has his specifications. Use this card as a character scope to list them:\\r\\n- Weariness"}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 5,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:20:38',
                'updated_at' => '2022-11-15 21:00:58',
            ),
            72 => 
            array (
                'id' => 75,
                'name' => '{"en":"Tree"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 20,
                'owner_id' => 1,
                'created_at' => '2022-11-16 01:49:43',
                'updated_at' => '2022-11-16 01:49:43',
            ),
            73 => 
            array (
                'id' => 77,
                'name' => '{"en":"Peccary"}',
            'desc' => '{"en":"A peccary (also javelina or skunk pig) is a medium-sized, pig-like hoofed mammal. A peccary is a medium-sized animal, with a strong resemblance to a pig. Like a pig, it has a snout ending in a cartilaginous disc, and eyes that are small relative to its head.\\r\\n\\r\\nPeccaries are social creatures that live in herds. They eat roots, grubs, and a variety of foods. They can identify each other by their strong odors. A group of peccaries that travel and live together is called a \\"squadron\\". A squadron of peccaries averages between six and nine members. Peccaries rely on their social structure to defend territory, protect against predators, regulate temperature, and interact socially.\\r\\n\\r\\nMayans kept herds of peccaries, using them in rituals and for food. They are kept as pets in many countries, in addition to being raised on farms as a source of food.\\r\\n\\r\\nPeccaries are omnivores and will eat insects, grubs, and occasionally small animals, although their preferred foods consist of roots, grasses, seeds, fruit, and cacti—particularly prickly pear. Pigs and peccaries can be differentiated by the shape of the canine tooth or tusk. In European pigs, the tusk is long and curves around itself, whereas in peccaries, the tusk is short and straight. The jaws and tusks of peccaries are adapted for crushing hard seeds and slicing them into plant roots, and they also use their tusks for defending against predators.\\r\\n\\r\\nPeccaries have scent glands below each eye and another on their backs. They use the scent to mark herd territories, which range from 30 to 280 hectares. They also mark other herd members with these scent glands by rubbing one against another. The pungent odor allows peccaries to recognize other members of their herd, despite their myopic vision. The odor is strong enough to be detected by humans, which earns the peccary the nickname of \\"skunk pig\\"."}',
                'is_public' => false,
                'image' => 'GSNmtoAMqvxYNXR40Rj05r2xW9b8f9e44cvCEOnd.jpg',
                'scope_id' => 19,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:14:26',
                'updated_at' => '2022-11-16 02:16:02',
            ),
            74 => 
            array (
                'id' => 78,
                'name' => '{"en":"Omnivorous"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 64,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:19:43',
                'updated_at' => '2022-11-16 02:19:43',
            ),
            75 => 
            array (
                'id' => 79,
                'name' => '{"en":"Skill"}',
                'desc' => '{"en":"Skills are the ability of a character to do something. The better the skill, the more successfully and efficiently he can perform this action.\\r\\n\\r\\nUse as a character deck scope for all his skills."}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 16,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:48:50',
                'updated_at' => '2022-11-16 02:49:50',
            ),
            76 => 
            array (
                'id' => 80,
                'name' => '{"en":"Survival"}',
                'desc' => '{"en":null}',
                'is_public' => true,
                'image' => NULL,
                'scope_id' => 79,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:54:14',
                'updated_at' => '2022-11-16 02:54:14',
            ),
            77 => 
            array (
                'id' => 81,
                'name' => '{"en":"Taming"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 79,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:56:34',
                'updated_at' => '2022-11-16 02:56:34',
            ),
            78 => 
            array (
                'id' => 82,
                'name' => '{"en":"Handling"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 79,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:03:44',
                'updated_at' => '2022-11-16 03:03:44',
            ),
            79 => 
            array (
                'id' => 83,
                'name' => '{"en":"Weapon"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 6,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:07:32',
                'updated_at' => '2022-11-16 03:07:32',
            ),
            80 => 
            array (
                'id' => 84,
                'name' => '{"en":"Spear"}',
                'desc' => '{"en":null}',
                'is_public' => false,
                'image' => NULL,
                'scope_id' => 83,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:08:36',
                'updated_at' => '2022-11-16 03:08:36',
            ),
            81 => 
            array (
                'id' => 76,
                'name' => '{"en":"Samauma"}',
                'desc' => '{"en":"This majestic creation of nature has been nicknamed as “Queen of the Forest,” the “Tree of Life”, “Mother of All Trees”, or “Ladder of Heaven”. When it comes to the diameter of the crown and roots, the Samaúma reigns supreme, reaching up to 50 meters in diameter at her canopy and 20 meters in diameter at her roots, which spread out to support the enormous tree. This vast canopy is laced with thousands of leaves that are grouped in umbrella-shaped tassels of five to seven pointed leaves each, hanging sovereignly above the forest.\\r\\n\\r\\nThis element is core to the spiritual character of this majestic being. The Samaúma tree is sacred to the Rainforest tribes. For them, it is a spirit that brings healing, a connection between Heaven and Earth. On it, you can climb up to the crown. All the spirits of the forest are united up there, that of plants, animals, and humans. There you can feel them."}',
                'is_public' => false,
                'image' => 'card_image/mB1QZT4cJcNXxpUjnnJjBcPLSYveBKkztmcMvM4k.jpg',
                'scope_id' => 75,
                'owner_id' => 1,
                'created_at' => '2022-11-16 01:57:55',
                'updated_at' => '2022-11-21 16:42:22',
            ),
            82 => 
            array (
                'id' => 55,
                'name' => '{"en":"Titu","ru":"Титу"}',
                'desc' => '{"en":"The boy from the forest tribe. Originally from the small settlement of Lanza Piya. Raised by parents and other residents of the settlement.\\r\\nHas a younger sister.\\r\\nSmart. Leader among peers.","ru":"Мальчик из лесного племени. Родом из небольшого поселения Ланза Пийя. Воспитан родителями и другими жителями поселения. Имеет младшую сестру. Умен и сообразителен. Лидер среди сверстников."}',
                'is_public' => false,
                'image' => 'card_image/iAp4X50I2pQFwAbFyzLjAPZD3520fhnJBJH5Y7lu.jpg',
                'scope_id' => 37,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:27:58',
                'updated_at' => '2022-11-21 19:24:51',
            ),
        ));
        
        
    }
}