<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cards')->delete();
        
        \DB::table('cards')->insert(array (
            0 => 
            array (
                'id' => 38,
                'name' => '{"en":"Eagle Nest","ru":"Орлиное Гнездо"}',
                'code' => NULL,
                'scope_id' => 1,
                'image' => NULL,
                'desc' => '{"en":"This ancient clan still lives in the depths of the unknown to this day. Finding the way to the inconspicuous is easy. But everyone who follows his own path of the heart will certainly meet him.","ru":"Этот древний клан и по сей день живет в самых недрах неизведанного. Найти дорогу к нему не просто. Но каждый, кто следует своему пути сердца однажды непременно встречается с ним"}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:16:54',
                'updated_at' => '2022-11-09 04:42:58',
            ),
            1 => 
            array (
                'id' => 39,
                'name' => '{"en":"Serpent Path","ru":"Тропа Змея"}',
                'code' => NULL,
                'scope_id' => 1,
                'image' => NULL,
                'desc' => '{"en":"The wise people follow the sacred path of the Serpent. Everyone who walks this path cultivates living blood in himself. Everyone who walks this path holds on to the other in order to honor this path together.","ru":"Мудрый народ следует священной Тропе Змея. Каждый, идущий по этой тропе, взращивает в себе кровь живую. Каждый, идущий по этой тропе, держится другого чтобы вместе чтить этот путь."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:09:50',
                'updated_at' => '2022-11-09 04:43:14',
            ),
            2 => 
            array (
                'id' => 31,
                'name' => '{"en":"Savanna"}',
                'code' => NULL,
                'scope_id' => 86,
                'image' => NULL,
                'desc' => '{"en":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:09:23',
                'updated_at' => '2022-11-24 18:38:02',
            ),
            3 => 
            array (
                'id' => 30,
                'name' => '{"en":"Seasonal Forest"}',
                'code' => NULL,
                'scope_id' => 86,
                'image' => NULL,
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:04:11',
                'updated_at' => '2022-11-24 18:39:02',
            ),
            4 => 
            array (
                'id' => 21,
                'name' => '{"en":"Human","ru":"Человек"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/Isbh3hI4bugGSEq7EPLxQ1UpmDXjzNNJHw0QX40K.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:15:03',
                'updated_at' => '2022-11-23 00:02:41',
            ),
            5 => 
            array (
                'id' => 29,
                'name' => '{"en":"Grassland","ru":"Луга"}',
                'code' => NULL,
                'scope_id' => 86,
                'image' => 'card/ldzd8hNWo2rGutngR0XvDNJOVUQtwJwDmXUkpov4.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:02:37',
                'updated_at' => '2022-11-25 04:24:12',
            ),
            6 => 
            array (
                'id' => 51,
                'name' => '{"en":"Jaguar"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/4398zjBN6BzZW25zi36LbDLBWw7wzZCCzkAju85H.jpg',
                'desc' => '{"en":"Jaguars spend much of their time on the ground. They use their padded paws to move silently through the forest floor. Although not quite as agile as a leopard, jaguars are capable of climbing trees to hunt or to rest. Jaguars are mostly nocturnal hunters. They use their excellent vision and sharp teeth to ambush prey and crush their skulls."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:59:15',
                'updated_at' => '2022-11-23 03:45:26',
            ),
            7 => 
            array (
                'id' => 59,
                'name' => '{"en":"Night","ru":"Ночь"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/iZcFdcfs740fG9vY4R6FnBZ6yy6dLhcxLwbsb6ds.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:56:02',
                'updated_at' => '2022-11-23 21:02:25',
            ),
            8 => 
            array (
                'id' => 58,
                'name' => '{"en":"Day","ru":"День"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/x4Kw60tYOzJK5uOpX9TkYOxLntmbZer12EN9fsgX.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:55:41',
                'updated_at' => '2022-11-23 21:10:09',
            ),
            9 => 
            array (
                'id' => 56,
                'name' => '{"en":"Poison Dart Frog"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/TAXT6RnYaPWLz55iDP9TR3GnP8pYJJ4mHtSaIuGD.webp',
                'desc' => '{"en":"Poison dart frogs are one of the planet’s most brightly colored animals. Depending on the species, they can be yellow, copper, gold, red, blue, green, black, or a combination of those colors. Their showy colors and startling designs help warn predators of the danger they impose. Within their skin, they store natural venom that can paralyze, or even kill, a predator.\\r\\n\\r\\nThis family of frogs includes some of the world’s most toxic species. The golden poison dart frog, for example, contains enough poison to kill 10 adult men. Indigenous cultures have used these frogs’ poison for centuries to coat the tip of their blow darts before hunting—a tradition that inspired the frogs’ common name.\\r\\n\\r\\nUnlike many other amphibians, poison dart frogs are diurnal. Most species are terrestrial but a few are arboreal. Poison dart frogs are insectivores, preferring to eat ants and other small insects that they can hunt among the leaf litter of the forest floor.\\r\\n\\r\\nMany species of poison dart frogs are very attentive parents. Often these parents choose the tiny pools of water held within bromeliads, and deposit a few tadpoles in each pool."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:22:08',
                'updated_at' => '2022-11-23 03:40:03',
            ),
            10 => 
            array (
                'id' => 57,
                'name' => '{"en":"Time","ru":"Время"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/gew8IFxzDggbw2k570pdHMIAvTwKj2h5k1gNdMK9.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 01:55:13',
                'updated_at' => '2022-11-23 21:10:44',
            ),
            11 => 
            array (
                'id' => 64,
                'name' => '{"en":"Diet","ru":"Диета"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/rX1xWIWZJ0zJzXkrShZh25jQ7pMWcGOuE3sONQT0.png',
                'desc' => '{"ru":"Различные существа нуждаются в различной пище для жизни и роста. Какая-то пища приносит больше энергии и сил, а какая-то вообще может причинить вред.\\r\\n\\r\\nПОДСКАЗКИ: Используйте как сферу для колоды существа со всеми продуктами, которые он употребляет. Это может быть еда, животные и так далее.","en":"Different creatures need different food to live and grow. Some food brings more energy and strength, and some can do damage.\\r\\n\\r\\nTIPS: Use as a scope for a creature deck with all the foods it consumes. It could be plants, animals, dishes, and so on."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:32:11',
                'updated_at' => '2022-11-23 21:00:10',
            ),
            12 => 
            array (
                'id' => 60,
                'name' => '{"en":"Action","ru":"Действие"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/ZZsaaHmdV5QOQd6rcwrOug6jKhm6HeQSYX4Z9pYc.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:02:13',
                'updated_at' => '2022-11-23 21:01:26',
            ),
            13 => 
            array (
                'id' => 78,
                'name' => '{"en":"Omnivorous"}',
                'code' => NULL,
                'scope_id' => 64,
                'image' => NULL,
                'desc' => '{"en":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:19:43',
                'updated_at' => '2022-11-16 02:19:43',
            ),
            14 => 
            array (
                'id' => 70,
                'name' => '{"en":"Nothing","ru":"Ничего"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => NULL,
                'desc' => '{"en":"The meaning of this card depends on the context.","ru":"Значение этой карты зависит от контекста."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:09:47',
                'updated_at' => '2022-11-23 20:48:37',
            ),
            15 => 
            array (
                'id' => 84,
                'name' => '{"en":"Spear","ru":"Копье"}',
                'code' => NULL,
                'scope_id' => 83,
                'image' => 'card/s1xmWboKBFs0g0usGKGAe6ELgQJPCUjsM5c8PNzp.jpg',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:08:36',
                'updated_at' => '2022-11-23 18:03:43',
            ),
            16 => 
            array (
                'id' => 9,
                'name' => '{"en":"Clan","ru":"Клан"}',
                'code' => NULL,
                'scope_id' => 85,
                'image' => 'card/s3HdOVmqD1LNQprc9X43t518pgtBU03wV4JPrABQ.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:08:04',
                'updated_at' => '2022-11-24 18:44:12',
            ),
            17 => 
            array (
                'id' => 8,
                'name' => '{"en":"Legend","ru":"Легенда"}',
                'code' => NULL,
                'scope_id' => 85,
                'image' => 'card/ZilOalIpLiHYHs1V9WTY2jy1yDCXBe2iGF9TjsB5.png',
                'desc' => '{"en":"A people without legends is like a tree without roots."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:07:52',
                'updated_at' => '2022-11-24 18:45:15',
            ),
            18 => 
            array (
                'id' => 10,
                'name' => '{"en":"Weariness","ru":"Усталость"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/QReWTHEz0FELexQleah1DfCeh0c4LdbQWAZian3z.png',
                'desc' => '{"en":"Even the heroes get tired over time. And the more weariness they accumulate, the harder it is for them to act. Weariness is removed by rest and food.","ru":"Даже герои со временем устают. И чем больше они накапливают усталости, тем труднее им действовать.\\r\\nУсталость снимается отдыхом и едой."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:36:47',
                'updated_at' => '2022-11-23 18:03:12',
            ),
            19 => 
            array (
                'id' => 5,
                'name' => '{"en":"Creature","ru":"Существо"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/6TM9RZ35XzuQdeEOLTxrGsWH4tOZTWvHKSL1hEzy.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:11:58',
                'updated_at' => '2022-11-22 23:55:25',
            ),
            20 => 
            array (
                'id' => 15,
                'name' => '{"en":"Settlement","ru":"Поселение"}',
                'code' => NULL,
                'scope_id' => 85,
                'image' => 'card/dgWw6Se0HB8pJ1dAndY1sbJLhD8cBe4v5Au7pNlb.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:26:20',
                'updated_at' => '2022-11-25 04:27:31',
            ),
            21 => 
            array (
                'id' => 12,
                'name' => '{"en":"Find","ru":"Находка"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/0tlgU14s6yXgkSmE2OBY1c3fbJvahnXHVnDuzPEW.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:39:42',
                'updated_at' => '2022-11-25 04:28:05',
            ),
            22 => 
            array (
                'id' => 22,
                'name' => '{"en":"Enemy","ru":"Враг"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/d2EKJ9u4Ila8SUmMncYME2ocXCus4LePe25GJsHq.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:49:41',
                'updated_at' => '2022-11-25 04:27:01',
            ),
            23 => 
            array (
                'id' => 11,
                'name' => '{"en":"Practice","ru":"Практика"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/2TgPhkQrN8CrilDvbZ6uFiKXn1irUXfXG3ceDKoP.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:36:58',
                'updated_at' => '2022-11-25 04:28:25',
            ),
            24 => 
            array (
                'id' => 1,
                'name' => '{"en":"Info","ru":"Инфо"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/UG4v2eNtJX1qh64ze451BBdrKs3wdkcO8urXOeQu.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-06 05:07:36',
                'updated_at' => '2022-11-23 00:33:08',
            ),
            25 => 
            array (
                'id' => 47,
                'name' => '{"en":"Lilika","ru":"Лилика"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/f2bVfwLmUJU8ie3VQZcgVLtxbVSGWi1CIl3zy8UV.jpg',
                'desc' => '{"en":"Although this young lady was nicknamed Beauty in the settlement, it should be noted that this is by no means her only virtue. Everyone is well aware of her talents for healing, especially after she began to help many of her tribe.\\r\\n\\r\\nIn addition, Lilika has always been distinguished by unprecedented seriousness and diligence in the study of plants and various healing agents. By her childhood years, she had already managed to accumulate considerable knowledge and skills in these areas.","ru":"Хотя эту молодую особу и прозвали в поселении Красавицей, нужно отметить что это вовсе не единственное ее достоинство. Всем хорошо известны ее таланты к целительству, особенно после того как она начала помогать многим из своего племени. \\r\\n\\r\\nКроме того, Лилика всегда отличалась небывалой серьезностью и старательностью в изучении растений и различных целебных средств. К своим детским годам она уже успела накопить немалые знания и навыки в этих сферах."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:36:25',
                'updated_at' => '2022-11-23 03:59:39',
            ),
            26 => 
            array (
                'id' => 48,
                'name' => '{"en":"Zaizi","ru":"Зайзи"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/bT0uWkvL6jl6BP2qLKMr1LQZERiCWeaAALGDOqbL.jpg',
                'desc' => '{"en":"This boy, like all other children in his village, was brought up not only by his parents but by the whole tribe. He has a sharp mind and sparkling humor. Loves to joke and make fun. Regularly plunges into various stories. He has a great talent for singing and artistic performances. Careless and careless.\\r\\n\\r\\nLike all his peers, Zaizi will soon have to go through his initiation ceremony. However, the boy does not think about it at all, because he is worried about completely different questions, let\'s say ... of a cordial nature ...\\r\\n\\r\\nFrom an early age, he leads a strong friendship with his peer Titu, with whom they spend a lot of time organizing all sorts of tricks.","ru":"Этот мальчик, как и все прочие дети в его поселке, воспитывался не только своими родителями, но и всем племенем. Обладает острым умом и искрометным юмором. Обожает шутить и подшучивать. Регулярно вляпывается в различные истории. Имеет большой талант к пению и артистическим выступлениям. Беспечен и легкомысленен.\\r\\n\\r\\nКак и всем его сверстникам, вскоре Зайзи предстоит пройти свою церемонию инициации. Впрочем, мальчик совсем не думает об этом, поскольку его беспокоят совершенно другие вопросы, скажем так... сердечного характера...\\r\\n\\r\\nС малых лет ведет крепкую дружбу со своим сверстником Титу, с которым они проводят много времени, организуя всяческие проделки."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:31:41',
                'updated_at' => '2022-11-23 03:52:29',
            ),
            27 => 
            array (
                'id' => 27,
                'name' => '{"en":"Spirit","ru":"Дух"}',
                'code' => NULL,
                'scope_id' => 7,
                'image' => 'card/zkCgmJEihVYiz0HaGWqGoLOTgLi9BnCERq7SE0yY.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:43:41',
                'updated_at' => '2022-11-22 23:48:56',
            ),
            28 => 
            array (
                'id' => 13,
                'name' => '{"en":"Encounter","ru":"Встреча"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/TGTqBwbQvMDQuGxpMxLuWimd5soM31zp40Xtc4rE.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-09 04:55:16',
                'updated_at' => '2022-11-23 00:16:12',
            ),
            29 => 
            array (
                'id' => 3,
                'name' => '{"en":"Event","ru":"Событие"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/g1Mlq38NS2PyQDlFVfgZ5vRaGJyPyQYBetlck1TT.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-09 04:51:54',
                'updated_at' => '2022-11-22 23:54:04',
            ),
            30 => 
            array (
                'id' => 20,
                'name' => '{"en":"Plant","ru":"Растение"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/ogKC1BZ2hwz9LzpLZpXoYZDJeUKxxyJqP8L93F1K.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:14:35',
                'updated_at' => '2022-11-23 00:15:28',
            ),
            31 => 
            array (
                'id' => 35,
                'name' => '{"ru":"Джунгли","en":"Rainforest"}',
                'code' => NULL,
                'scope_id' => 86,
                'image' => 'card/9gCDRRK6dylcNDwheAwIf0LU3KqUd55NJBvembGE.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:56:49',
                'updated_at' => '2022-11-24 18:35:31',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => '{"en":"Marsh","ru":"Marsh"}',
                'code' => NULL,
                'scope_id' => 62,
                'image' => 'card/nogiFfrGJ3cpafs9DMaor3eduIfhBemQuQqLBjFb.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:27:08',
                'updated_at' => '2022-11-24 17:35:55',
            ),
            33 => 
            array (
                'id' => 24,
                'name' => '{"en":"Predator","ru":"Хищник"}',
                'code' => NULL,
                'scope_id' => 64,
                'image' => 'card/FtJKyOVxR31rEA5bPOw3P8F29UapXzkRB2buFeHC.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:54:28',
                'updated_at' => '2022-11-25 04:26:45',
            ),
            34 => 
            array (
                'id' => 25,
                'name' => '{"en":"Herbivore","ru":"Травоядное"}',
                'code' => NULL,
                'scope_id' => 64,
                'image' => 'card/ELlE2MQJebwLb8H81wHz4fluErAJglepbilfhqTO.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:58:18',
                'updated_at' => '2022-11-25 04:26:08',
            ),
            35 => 
            array (
                'id' => 46,
                'name' => '{"en":"Araki","ru":"Араки"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/iSbS179w51guQr6uQzsnSX5HIxAst8msz80pTOV1.jpg',
                'desc' => '{"en":"This is a bright and noisy toucan, the favorite pet of Rekko, Titu\'s father.","ru":"Это яркий и шумный тукан, любимый питомец Рекко, отца Титу."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:29:38',
                'updated_at' => '2022-11-23 03:32:45',
            ),
            36 => 
            array (
                'id' => 2,
                'name' => '{"en":"Quest","ru":"Квест"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/f18Y5XNVmbFPHixcoFU9hE2Bt8CULngklAVij9I0.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:33:42',
                'updated_at' => '2022-11-22 23:51:44',
            ),
            37 => 
            array (
                'id' => 43,
                'name' => '{"en":"Airi","ru":"Айри"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/oRIzrl2B7SSE7adqq2ZPUdiAVwTij1tonp3Byyib.jpg',
                'desc' => '{"en":"Many tribes of the Rainforest believe in the existence of a powerful and wise spirit who is the guardian and protector of the jungle, as well as all its inhabitants.","ru":"Многие племена Тропического Леса верят в существование могущественного и мудрого духа, который является хранителем и защитником джунглей, а также всех его обитателей."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:35:19',
                'updated_at' => '2022-11-23 03:57:33',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => '{"en":"Totem Quest","ru":"Поиски Тотема"}',
                'code' => NULL,
                'scope_id' => 2,
                'image' => 'card/bCsDfWXKHL2fSyRGNZ0raZTxp8BTBzxb3yd13Uji.jpg',
                'desc' => '{"en":"To pass the initiation ceremony, Titu needs to find his totem of power. The difficulty is that the boy so far has a rather poor understanding of what it is and where to look for it.\\r\\n\\r\\nTherefore, at every opportunity, he needs to extract any information on this topic.","ru":"To pass the initiation ceremony, Titu needs to find his totem of power. The difficulty is that the boy so far has a rather poor understanding of what it is and where to look for it.\\r\\n\\r\\nTherefore, at every opportunity, he needs to extract any information on this topic."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:41:18',
                'updated_at' => '2022-11-23 04:01:22',
            ),
            39 => 
            array (
                'id' => 45,
                'name' => '{"en":"Pua","ru":"Пуа"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/uGJNkHgZF7L46gEzDltCrsIAvpcjWWFnYsqdidjk.jpg',
                'desc' => '{"en":"Perhaps this is the most educated boy in the entire settlement. From an early age, he showed great interest in the legends and knowledge of his tribe. This is one of the few guys who can read and write well and loves to do it.\\r\\n\\r\\nMany, not without reason, believe that the old keeper is preparing this boy to replace him.","ru":"Пожалуй, это самый образованный мальчик во всем поселении. С малых лет он проявил большой интерес к легендам и знаниям своего племени. Это один из немногих ребят, кто умеет хорошо читать и писать и любит этим заниматься.\\r\\n\\r\\nМногие не без оснований считают, что старый хранитель готовит этого мальчика себе на смену."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:33:05',
                'updated_at' => '2022-11-23 03:54:51',
            ),
            40 => 
            array (
                'id' => 7,
                'name' => '{"en":"Power","ru":"Сила"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/2QBxEsJrrdEYGHmt9vM0Zy848y2T7m9SjG7unwJm.png',
                'desc' => '{"en":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:43:27',
                'updated_at' => '2022-11-22 23:50:42',
            ),
            41 => 
            array (
                'id' => 14,
                'name' => '{"en":"Wilderness","ru":"Дикие Земли"}',
                'code' => NULL,
                'scope_id' => 85,
                'image' => 'card/6LszdfAv403cEVxgvgjvZXBLTmu1n63rSpjEpbF5.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:24:51',
                'updated_at' => '2022-11-25 04:27:45',
            ),
            42 => 
            array (
                'id' => 26,
                'name' => '{"en":"Frugivorous","ru":"Плодоядное"}',
                'code' => NULL,
                'scope_id' => 64,
                'image' => 'card/bYKHIqJzZMuydhIQRobsRXEtZY5jphlMdp2bo7IA.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-12 04:23:13',
                'updated_at' => '2022-11-25 04:31:05',
            ),
            43 => 
            array (
                'id' => 18,
                'name' => '{"en":"Insect","ru":"Насекомое"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/baIHDjIYRBSJp9FIuyk2lPcA5JVcpAMk8pNIV1fS.png',
                'desc' => '{"en":"Insects are the most diverse group of animals; they include more than a million described species and represent more than half of all known living organisms. The total number of extant species is estimated at between six and ten million; potentially over 90% of the animal life forms on Earth are insects.\\r\\n\\r\\nInsect pollinators are essential to the life cycle of many flowering plant species on which most organisms, including humans, are at least partly dependent; without them, the terrestrial portion of the biosphere would be devastated. Many insects are considered ecologically beneficial as predators and a few provide direct economic benefit. Silkworms produce silk and honey bees produce honey and both have been domesticated by humans. Insects are consumed as food in 80% of the world\'s nations, by people in roughly 3000 ethnic groups"}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:18:53',
                'updated_at' => '2022-11-23 00:22:39',
            ),
            44 => 
            array (
                'id' => 42,
                'name' => '{"en":"Knowledge","ru":"Знание"}',
                'code' => NULL,
                'scope_id' => 7,
                'image' => 'card/xTrHUSM4j0SMJylDkTAh7BEIbN9cPuweBUTAgQMh.png',
                'desc' => '{"en":"Nothing is free in this world, and the acquisition of knowledge is the most difficult of all tasks that a person can face.\\r\\n\\r\\nA character can have and accumulate knowledge about a variety of things, be it skills, legends, secrets and etc. This knowledge affects the capabilities of the character and the situations in which he finds himself.\\r\\n\\r\\nTIPS: Use as a character deck sphere for all the things that character knows about.","ru":"В этом мире нет ничего бесплатного, и получение знаний — самая трудная из всех задач, с которыми может столкнуться человек.\\r\\n\\r\\nПерсонаж может иметь и накапливать знания о самых разных вещах, будь то навыки, легенды, секреты. Эти знания влияют на возможности персонажа и на ситуации, в которые он попадает.\\r\\n\\r\\nПОДСКАЗКИ: Используй как сферу с колодой персонажа для всех вещей, о которых знает этот персонаж."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 15:40:03',
                'updated_at' => '2022-11-23 21:18:18',
            ),
            45 => 
            array (
                'id' => 82,
                'name' => '{"en":"Handling","ru":"Сноровка"}',
                'code' => NULL,
                'scope_id' => 79,
                'image' => 'card/XACk5e1HLvJcsiXepk4alZXgzYSC6rlFnRfXjFNi.png',
                'desc' => '{"ru":"Под сноровкой здесь подразумевается умение обращаться с различными предметами, инструментами, оружием и тому подобным.\\r\\n\\r\\nЭтот навык имеет специализации для разных предметов, с которыми он применяется. Чем больше персонаж  практикует сноровку с тем, или иным предметом, тем больше растет данная специализация и весь навык в целом.\\r\\n\\r\\nПОДСКАЗКИ: Используй как сферу для колоды персонажа с различными предметами, с которыми он умеет обращаться.","en":"Handling here means the skill to handle various objects, tools, and the like.\\r\\n\\r\\nThis skill has specializations for the different items it is used with. The more a character practices handling one or another item, the more this specialization and the whole skill as a whole grows.\\r\\n\\r\\nTIPS: Use as a scope for your character\'s deck with various items that he knows how to use."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:03:44',
                'updated_at' => '2022-11-23 19:22:04',
            ),
            46 => 
            array (
                'id' => 74,
                'name' => '{"en":"Flashback","ru":"Воспоминание"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/J4HLzxiwpF9dARr1hZDoUwnIKpfcb44VQkkQWz09.png',
                'desc' => '{"ru":"Время от времени мы все вспоминаем разные вещи. Иногда воспоминания приходят сами, внезапно и неожиданно. Иногда они содержат необходимую помощь или важные подсказки.","en":"From time to time we all remember different things. Sometimes flashbacks come by themselves, suddenly and unexpectedly. Sometimes they contain necessary help or important hints."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:26:20',
                'updated_at' => '2022-11-23 18:42:02',
            ),
            47 => 
            array (
                'id' => 72,
                'name' => '{"en":"Fail","ru":"Провал"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/MbRnrUlQ6ypOuIMK1xP4dgxxc8e4bxLf3qI5SkQN.png',
                'desc' => '{"en":"The meaning of this card depends on the context.","ru":"Значение этой карты зависит от контекста."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:12:25',
                'updated_at' => '2022-11-25 01:17:41',
            ),
            48 => 
            array (
                'id' => 94,
                'name' => '{"en":"New Moon","ru":"Новолуние"}',
                'code' => NULL,
                'scope_id' => 91,
                'image' => 'card/9Cz86Z3d0mlOneA6cXnPxqQlstOqNBxrVbmf8XjH.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:42:25',
                'updated_at' => '2022-11-25 04:14:51',
            ),
            49 => 
            array (
                'id' => 92,
                'name' => '{"en":"Waxing Moon","ru":"Убывающая Луна"}',
                'code' => NULL,
                'scope_id' => 91,
                'image' => 'card/kZpaG1N1C3e4JmPgw5MXMxT78ofJyjTZYQleS2y7.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:36:04',
                'updated_at' => '2022-11-25 04:15:40',
            ),
            50 => 
            array (
                'id' => 41,
                'name' => '{"en":"Traveling","ru":"Путешествие"}',
                'code' => NULL,
                'scope_id' => 79,
                'image' => 'card/mseTJIuag5KBZ2p9aNoF7u6hcA8ZigwCTj0JzfJY.png',
                'desc' => '{"en":"As a rule, the hero does not sit in one place for a long time. Most of the time he travels. Therefore, this skill is very important and useful for him.\\r\\n\\r\\nThis skill has a specialization for each biome that the hero or character travels through. The more a character wanders around a given biome, the more this specialization and this entire skill as a whole grows.\\r\\n\\r\\nTIPS:\\r\\n- Use as a scope for your character deck to list all skill specializations and their levels.\\r\\n- Use as a scope for a biome deck to list all the events that can happen while traveling through a given biome.","ru":"Как правило, герой не сидит долго на одном месте. Большую часть времени он путешествует. Поэтому этот навык для него очень важен и полезен.\\r\\n\\r\\nЭтот навык имеет специализацию для каждого биома, по которому путешествует герой или персонаж. Чем больше персонаж странствует по данному биому, тем больше растет данная специализация и весь этот навык в целом.\\r\\n\\r\\nСОВЕТЫ:\\r\\n- Используйте в качестве сферы для колоды персонажа, чтобы перечислить все специализации навыка и их уровни.\\r\\n- Используйте в качестве сферы для колоды биома, чтобы перечислить все события, которые могут произойти во время путешествия по данному биому."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 13:55:09',
                'updated_at' => '2022-11-23 21:32:34',
            ),
            51 => 
            array (
                'id' => 99,
                'name' => '{"en":"Deep Forest","ru":"Реликтовые Джунгли"}',
                'code' => NULL,
                'scope_id' => 87,
                'image' => 'card/oXhBtbwowwjZl719wFncIr6nepLbW0z7jgbDuVgu.png',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-12-04 16:00:09',
                'updated_at' => '2022-12-04 20:28:14',
            ),
            52 => 
            array (
                'id' => 100,
                'name' => '{"en":"Savanna Tract","ru":"Засушливый Тракт"}',
                'code' => NULL,
                'scope_id' => 87,
                'image' => 'card/AZkPqM2WN5LEjgw7Z4xsuxi24XnpxWj6KU6jTt8c.jpg',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-12-04 16:27:50',
                'updated_at' => '2022-12-04 20:29:00',
            ),
            53 => 
            array (
                'id' => 98,
                'name' => '{"en":"Serpent\'s Lair","ru":"Гнездо Змея"}',
                'code' => NULL,
                'scope_id' => 97,
                'image' => 'card/ELT3zt2eYiaGldxfEiX7dwDbJsCIiTDn4pW6hOaP.jpg',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-12-04 07:37:34',
                'updated_at' => '2022-12-04 20:29:37',
            ),
            54 => 
            array (
                'id' => 33,
                'name' => '{"en":"River of Birth","ru":"Река Рождения"}',
                'code' => NULL,
                'scope_id' => 87,
                'image' => 'card/lSd8Dx9csBlUWKhA1CyiX4wF1x5SQuSCENHW4FDK.jpg',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:25:49',
                'updated_at' => '2022-12-04 20:35:01',
            ),
            55 => 
            array (
                'id' => 49,
                'name' => '{"en":"Scarlet Macaw"}',
                'code' => NULL,
                'scope_id' => 17,
                'image' => 'card/3CgQYAboppkKJh94ly2F2fayfR8Abhsr1bfW3uoj.jpg',
                'desc' => '{"en":"Macaws are the largest parrots in the world! This beautiful macaw has a creamy white, almost featherless face, with bright red plumage covering most of its body, wings, and long tail. Brilliant blue and yellow feathers also adorn the lower wings. The bird’s strong beak is adapted to breaking hard nuts found in the rainforest.\\r\\n\\r\\nMacaws also mate for life, nesting from January through April in the holes of dead canopy trees. Mated adults lay up to two eggs per year, and preen each other and their offspring for hours, cleaning bugs from their feathers.\\r\\n\\r\\nNuts, leaves, berries and seeds from the rainforest make up the bulk of the scarlet macaw’s diet. Its strong, hooked beak is perfect for breaking nuts and seeds. Interestingly, the scarlet macaw can eat fruits toxic enough to kill other animals. This could be because they also eat large amounts of clay, which is thought to neutralize plant poisons."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 04:20:48',
                'updated_at' => '2022-11-23 03:49:44',
            ),
            56 => 
            array (
                'id' => 52,
                'name' => '{"en":"Brown Sloth"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/8zH2IpSZfR5fzvKwoJQnI7liGc7nZnRxTALXpucq.jpg',
                'desc' => '{"en":"This cat-sized mammal, typically weighing 8 – 9 pounds, has a round head, a short snout, small eyes, long legs, tiny ears, and a stubby tail. Sloths have long, coarse fur that is light brown in color but often appears green due to the blue-green algae that grow there. Instead of toes, their front and hind feet have three curved claws that allow them to easily hook onto tree branches and hang upside-down. Sloths can rotate their heads nearly 90 degrees, and their mouths are shaped so they look like they are always smiling.\\r\\n\\r\\nTheir algae-covered fur helps camouflage the sloth in its forest environment. Sloths spend nearly all of their time in trees, descending to the ground only once a week to defecate.\\r\\n\\r\\nSloths are among the slowest-moving animals on Earth; they can swim but are virtually unable to walk. This makes them an easy target for jaguars, eagles, and people that hunt sloths for their meat."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:48:34',
                'updated_at' => '2022-11-23 03:44:43',
            ),
            57 => 
            array (
                'id' => 75,
                'name' => '{"en":"Tree","ru":"Дерево"}',
                'code' => NULL,
                'scope_id' => 20,
                'image' => 'card/IbaCFQfHfY7KeSrLgyQNSZBHSoLhbGvDPL7N8eaN.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 01:49:43',
                'updated_at' => '2022-11-23 21:01:52',
            ),
            58 => 
            array (
                'id' => 89,
                'name' => '{"en":"Hut","ru":"Хижина"}',
                'code' => NULL,
                'scope_id' => 90,
                'image' => 'card/97qhDxjwkkPAXaxFYvL38e7axEBRUuraPzBptypw.png',
                'desc' => '{"en":"A Place inside a certain Hut. What kind of Hut it is, who owns it, where it is located and its other characteristics depend on the context of the game.","ru":"Место внутри определенной хижины. Что это за хижина, кому она принадлежит, где она расположена и другие ее характеристики зависят от контекста игры."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 21:04:46',
                'updated_at' => '2022-11-25 04:18:24',
            ),
            59 => 
            array (
                'id' => 96,
                'name' => '{"en":"Year","ru":"Год"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/X24HeU13Bom5zMH4dmMWrj3k2gvhAi8iG5mFuC1Z.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:56:01',
                'updated_at' => '2022-11-25 04:13:49',
            ),
            60 => 
            array (
                'id' => 16,
                'name' => '{"en":"Character","ru":"Персонаж"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/4TJrtuwnmgW2KotswgAJO8U2ML8OgawEoJguQPd0.png',
                'desc' => '{"en":"Any creature that plays an important role in this book is a character. Each character has a name, skills, knowledge, features, and other characteristics.\\r\\n\\r\\nAlso, each character has his specifications. Use this card as a character scope to list them:\\r\\n- Weariness"}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:20:38',
                'updated_at' => '2022-11-22 23:58:25',
            ),
            61 => 
            array (
                'id' => 90,
                'name' => '{"en":"Scene","ru":"Сцена"}',
                'code' => NULL,
                'scope_id' => 4,
                'image' => 'card/U8JqwjGBHernRKnTZzcuEaMwWGGDZw3bFzBxzfJt.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 23:30:30',
                'updated_at' => '2022-11-25 04:16:50',
            ),
            62 => 
            array (
                'id' => 17,
                'name' => '{"en":"Bird","ru":"Птица"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/2kAnIEBToqa7pMqAtwNK45RtmyyMyibXP3Iq9WHA.png',
                'desc' => '{"en":"Birds are a group of warm-blooded vertebrates, characterized by feathers, toothless beaked jaws, the laying of hard-shelled eggs, a high metabolic rate, a four-chambered heart, and a strong yet lightweight skeleton. Birds live worldwide and range in size from the bee hummingbird to the ostrich. There are about ten thousand living species, more than half of which are passerine, or \\"perching\\" birds.\\r\\n\\r\\nMany social species pass on knowledge across generations, which is considered a form of culture. Birds are social, communicating with visual signals, calls, and songs, and participating in such behaviours as cooperative breeding and hunting, flocking, and mobbing of predators."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:17:34',
                'updated_at' => '2022-11-22 21:52:17',
            ),
            63 => 
            array (
                'id' => 86,
                'name' => '{"en":"Biome","ru":"Биом"}',
                'code' => NULL,
                'scope_id' => 4,
                'image' => 'card/VfnN0pu6Z23vdu974UNmlQ1jAz7SvzJsKK615rGz.png',
                'desc' => '{"en":"A Biome is an assemblage of ecosystems in the same natural and climatic zone, usually having some major vegetation type or other characteristic feature, such as in a landscape.\\r\\n\\r\\nThe main types of Biomes are as follows:\\r\\n- Wetland\\r\\n- Grassland\\r\\n- Rainforest\\r\\n- Tundra\\r\\n- Taiga\\r\\n- Savannah\\r\\n- and others.\\r\\n\\r\\nTIPS:\\r\\n- Use as a scope for the Hero\'s deck to indicate his current Biome.\\r\\n- Use as a scope for the Creature\'s deck to describe the Biomes in which it can be found.","ru":"Биом - это совокупность экосистем, находящихся в одной природно-климатической зоне, обычно с каким-либо основным типом растительности или другой характерной особенностью, например, в ландшафте.\\r\\n\\r\\nОсновные типы биомов следующие:\\r\\n- Водные Земли\\r\\n- Равнины\\r\\n- Джунгли\\r\\n- Тундра\\r\\n- Тайга\\r\\n- Саванна\\r\\n- и другие.\\r\\n\\r\\nПОДСКАЗКИ:\\r\\n- Используйте в качестве сферы для колоды существа, чтобы описать биомы, в которых его можно обнаружить."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 18:33:40',
                'updated_at' => '2022-11-24 19:22:07',
            ),
            64 => 
            array (
                'id' => 66,
                'name' => '{"en":"Snake","ru":"Змея"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/dqkmxlLwIHVfPHxDPYHBEbercczTQoB02s7X7cfp.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:49:38',
                'updated_at' => '2022-11-23 20:49:59',
            ),
            65 => 
            array (
                'id' => 50,
                'name' => '{"en":"Blue Morpho Butterfly"}',
                'code' => NULL,
                'scope_id' => 18,
                'image' => 'card/793kqF58KXqPzMhgoNzVea7ClnLZhPpbXKN47Wzv.jpg',
                'desc' => '{"en":"With its brilliant, iridescent blue wings, the blue morpho butterfly flutters through the rainforest canopy. The many “eyespots” on its brown underside trick predators into thinking the butterfly is a large predator.\\r\\n\\r\\nThe blue morpho’s diet changes throughout each stage of its lifecycle. As a caterpillar, it chews leaves of many varieties but prefers to dine on plants in the pea family. When it becomes a butterfly it can no longer chew, but drinks its food instead. Adults use a long, protruding mouthpart called a proboscis as a drinking straw to sip the juice of rotting fruit, the fluids of decomposing animals, tree sap, fungi, and wet mud. Blue morphos taste fruit with sensors on their legs, and they “taste-smell” the air with their antennae, which serve as a combined tongue and nose.\\r\\n\\r\\nBirds like the jacamar and flycatcher are the adult butterfly’s natural predators."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 02:19:01',
                'updated_at' => '2022-11-23 03:47:09',
            ),
            66 => 
            array (
                'id' => 93,
                'name' => '{"en":"Waning Moon","ru":"Растущая Луна"}',
                'code' => NULL,
                'scope_id' => 91,
                'image' => 'card/9qxpmR1XCyPLboty9VIKTB63325eyn0WMrYQUR0G.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:38:31',
                'updated_at' => '2022-11-25 04:15:17',
            ),
            67 => 
            array (
                'id' => 67,
                'name' => '{"en":"Evening","ru":"Вечер"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/mt3ysCBSNZTwoLJ4oEFDcPrI8Z5xoB09JUpnUiUb.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:53:18',
                'updated_at' => '2022-11-23 20:49:30',
            ),
            68 => 
            array (
                'id' => 81,
                'name' => '{"en":"Taming","ru":"Приручение"}',
                'code' => NULL,
                'scope_id' => 79,
                'image' => 'card/uZlgLsjkMUXVGkOTWCqUN6pslNri1KgE5lQI2BE0.png',
                'desc' => '{"ru":"Умение находить общий язык с самыми различными животными и приручать их, делая верными союзниками и друзьями может очень пригодится в незнакомых диких землях.\\r\\n\\r\\nЭтот навык имеет специализации для каждого вида животных, для которых он применяется. Чем больше персонаж практикует приручение того или иного животного, тем больше растет данная специализация и весь навык в целом.\\r\\n\\r\\nПОДСКАЗКИ: Используй как сферу для колоды персонажа с различными животными, для которых персонаж имеет навык приручения.","en":"The ability to find a common language with a variety of animals and tame them, making them loyal allies and friends can be very useful in unfamiliar Wilderness.\\r\\n\\r\\nThis skill has specializations for each type of animal it is applied to. The more a character practices taming a particular animal, the more this specialization and the skill as a whole grows.\\r\\n\\r\\nTIPS: Use as a scope for your character deck with various animals for which the character has the taming skill."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:56:34',
                'updated_at' => '2022-11-23 19:17:44',
            ),
            69 => 
            array (
                'id' => 85,
                'name' => '{"en":"Folk","ru":"Народ"}',
                'code' => NULL,
                'scope_id' => 4,
                'image' => 'card/gxkKNqJE7VGnuDY4yRsGNj9pWYrZ85GfHYutqHin.png',
                'desc' => '{"en":"Folk refers to the inhabitants of a particular area, with its own characteristics, history, culture, population density, and so on.\\r\\n\\r\\nDepending on population density, the following types of folk are distinguished:\\r\\n- Wilderness\\r\\n- Settlements\\r\\n- Villages\\r\\n- Towns\\r\\n- Cities\\r\\n- and others\\r\\n\\r\\nHINTS:\\r\\n- Use as a scope for the Hero\'s deck to indicate Folk for the current Place.","ru":"Под народом подразумеваются жители определенной местности, имеющие свои особенности, историю, культуру, плотность населения и так далее.\\r\\n\\r\\nВ зависимости от плотности населения выделяют следующие виды населения:\\r\\n- Дикие Земли\\r\\n- Поселения\\r\\n- Деревни\\r\\n- Городки\\r\\n- Города\\r\\n- и другие\\r\\n\\r\\nПОДСКАЗКИ:\\r\\n- Используйте в качестве сферы для колоды Героя, чтобы указать население данного места."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 18:22:30',
                'updated_at' => '2022-11-24 19:29:18',
            ),
            70 => 
            array (
                'id' => 62,
                'name' => '{"en":"Wetland","ru":"Водные Земли"}',
                'code' => NULL,
                'scope_id' => 86,
                'image' => 'card/sjjpb9gbUYNiciBpwe6rjR67vaizp8EPRHHSJcv3.png',
            'desc' => '{"en":"A wetland is a biome that is flooded or saturated by water, either permanently (for years or decades) or seasonally (for weeks or months). The primary factor that distinguishes Wetlands from terrestrial land forms or water bodies is the characteristic vegetation of aquatic plants, adapted to the unique anoxic hydric soils. The water in Wetlands is either freshwater, brackish, or saltwater. Wetlands are considered among the most biologically diverse of all ecosystems, serving as home to a wide range of plant and animal species.\\r\\n\\r\\nThere are four main kinds of this biome:\\r\\n- Marsh\\r\\n- Swamp\\r\\n- Bog\\r\\n- Fen\\r\\n\\r\\nThese main Wetland types are classified based on the dominant plants and\\/or the source of the water. For example, Marshes are wetlands dominated by emergent vegetation such as reeds, cattails, and sedges. Swamps are ones dominated by woody vegetation such as trees and shrubs.","ru":"Водные Земли — это особый биом, который затопляется или насыщается водой либо постоянно (в течение многих лет или десятилетий), либо сезонно (в течение недель или месяцев). Основным фактором, отличающим Водные Земли от других биомов, является характерная водная растительность, адаптированная к уникальным бескислородным влажным почвам. Вода в Водных Землях бывает пресной, солоноватой или соленой.  Этот биом считается одним из самых биологически разнообразных из всех биомов, он служит домом для широкого круга видов растений и животных.\\r\\n\\r\\nСуществует четыре основных вида:\\r\\n - Marsh\\r\\n - Swamp\\r\\n - Bog\\r\\n - Fen.\\r\\n\\r\\nЭти четыре основных вида Водных Земель классифицируются на основе преобладающих растений и\\/или источника воды. Например, Marshes представляют собой Водные Земли, на которых преобладает надводная растительность, такая как тростник, рогоз и осока. В свою очередь в Swamps преобладает древесная растительность, такая как деревья и кустарники."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:24:58',
                'updated_at' => '2022-11-24 18:34:36',
            ),
            71 => 
            array (
                'id' => 95,
                'name' => '{"en":"Full Moon","ru":"Полнолуние"}',
                'code' => NULL,
                'scope_id' => 91,
                'image' => 'card/IYsgKNml5LBHrhkI1F4e19zfuI47ERxT7QMTXTdG.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:52:29',
                'updated_at' => '2022-11-25 04:14:23',
            ),
            72 => 
            array (
                'id' => 77,
                'name' => '{"en":"Peccary"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/3kaGDfMeNmvrkTxqo0isNryuxkgPdA1ogkTdCRAh.jpg',
            'desc' => '{"en":"A peccary (also javelina or skunk pig) is a medium-sized, pig-like hoofed mammal. A peccary is a medium-sized animal, with a strong resemblance to a pig. Like a pig, it has a snout ending in a cartilaginous disc, and eyes that are small relative to its head.\\r\\n\\r\\nPeccaries are social creatures that live in herds. They eat roots, grubs, and a variety of foods. They can identify each other by their strong odors. A group of peccaries that travel and live together is called a \\"squadron\\". A squadron of peccaries averages between six and nine members. Peccaries rely on their social structure to defend territory, protect against predators, regulate temperature, and interact socially.\\r\\n\\r\\nMayans kept herds of peccaries, using them in rituals and for food. They are kept as pets in many countries, in addition to being raised on farms as a source of food.\\r\\n\\r\\nPeccaries are omnivores and will eat insects, grubs, and occasionally small animals, although their preferred foods consist of roots, grasses, seeds, fruit, and cacti—particularly prickly pear. Pigs and peccaries can be differentiated by the shape of the canine tooth or tusk. In European pigs, the tusk is long and curves around itself, whereas in peccaries, the tusk is short and straight. The jaws and tusks of peccaries are adapted for crushing hard seeds and slicing them into plant roots, and they also use their tusks for defending against predators.\\r\\n\\r\\nPeccaries have scent glands below each eye and another on their backs. They use the scent to mark herd territories, which range from 30 to 280 hectares. They also mark other herd members with these scent glands by rubbing one against another. The pungent odor allows peccaries to recognize other members of their herd, despite their myopic vision. The odor is strong enough to be detected by humans, which earns the peccary the nickname of \\"skunk pig\\"."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:14:26',
                'updated_at' => '2022-11-23 03:35:47',
            ),
            73 => 
            array (
                'id' => 76,
                'name' => '{"en":"Samauma"}',
                'code' => NULL,
                'scope_id' => 75,
                'image' => 'card/mB1QZT4cJcNXxpUjnnJjBcPLSYveBKkztmcMvM4k.jpg',
                'desc' => '{"en":"This majestic creation of nature has been nicknamed as “Queen of the Forest,” the “Tree of Life”, “Mother of All Trees”, or “Ladder of Heaven”. When it comes to the diameter of the crown and roots, the Samaúma reigns supreme, reaching up to 50 meters in diameter at her canopy and 20 meters in diameter at her roots, which spread out to support the enormous tree. This vast canopy is laced with thousands of leaves that are grouped in umbrella-shaped tassels of five to seven pointed leaves each, hanging sovereignly above the forest.\\r\\n\\r\\nThis element is core to the spiritual character of this majestic being. The Samaúma tree is sacred to the Rainforest tribes. For them, it is a spirit that brings healing, a connection between Heaven and Earth. On it, you can climb up to the crown. All the spirits of the forest are united up there, that of plants, animals, and humans. There you can feel them."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-16 01:57:55',
                'updated_at' => '2022-11-21 16:42:22',
            ),
            74 => 
            array (
                'id' => 69,
                'name' => '{"en":"Armadillo"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/lZh2CJUIDYfnoySp5xi423LWXiZVCnsPM0Y4cYC8.jpg',
            'desc' => '{"en":"Armadillos are characterized by a leathery armor shell and long, sharp claws for digging. They have short legs but can move quite quickly. When threatened by a predator, Tolypeutes species frequently roll up into a ball; they are the only species of armadillo capable of this.\\r\\n\\r\\nThe diets of different armadillo species vary but consist mainly of insects, grubs, and other invertebrates. Some species, however, feed almost entirely on ants and termites.\\r\\n\\r\\nThey are prolific diggers. Many species use their sharp claws to dig for food, such as grubs, and to dig dens. The nine-banded armadillo prefers to build burrows in moist soil near the creeks, streams, and arroyos around which it lives and feeds.\\r\\n\\r\\nArmadillos have very poor eyesight and use their keen sense of smell to hunt for food. They use their claws for digging and finding food, as well as for making their homes in burrows. They dig their burrows with their claws, making only a single a corridor the width of the animal\'s body.\\r\\n\\r\\nThe underside of the animal is never armored and is simply covered with soft skin and fur. This armor-like skin appears to be an important defense for many armadillos, although most escape predators by fleeing (often into thorny patches, from which their armor protects them) or digging to safety. Only the South American three-banded armadillos (Tolypeutes) rely heavily on their armor for protection.\\r\\n\\r\\nArmadillos have short legs but can move quite quickly. The nine-banded armadillo is noted for its movement through water which is accomplished via two different methods: it can walk underwater for short distances, holding its breath for as long as six minutes; also, crossing larger bodies of water, it is capable of increasing its buoyancy by swallowing air, inflating its stomach and intestines"}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-13 18:04:42',
                'updated_at' => '2022-11-23 03:37:24',
            ),
            75 => 
            array (
                'id' => 68,
                'name' => '{"en":"Morning","ru":"Утро"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/d4L6nB39jIdthxzqUnLzm87sgik1PLSwpYgI18F4.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:54:10',
                'updated_at' => '2022-11-23 20:49:04',
            ),
            76 => 
            array (
                'id' => 73,
                'name' => '{"en":"Damage","ru":"Вред"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/Yz12TOspsV6q1PCle10wtSc1vpugPFmnnC961hi0.png',
                'desc' => '{"en":"Damage can be obtained in a variety of ways. And sometimes quite unexpectedly and suddenly. Often, wounds and injuries complicate the life of a hero quite a lot and bring additional difficulties. So, try to find ways to heal the damage as soon as you can.\\r\\n\\r\\nTIPS: Use as a scope for a deck of all hero or character damage.","ru":"Повреждения можно получить самыми разными способами. Иногда совершенно неожиданно и внезапно. Зачастую раны и травмы довольно сильно усложняют жизнь героя и приносят ему дополнительные трудности. Поэтому, постарайся найти способ исцелить полученный вред как можно быстрее.\\r\\n\\r\\nСОВЕТЫ: Используй как сферу для колоды всех повреждений героя или персонажа."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:16:42',
                'updated_at' => '2022-11-23 18:54:50',
            ),
            77 => 
            array (
                'id' => 71,
                'name' => '{"en":"Success","ru":"Успех"}',
                'code' => NULL,
                'scope_id' => 3,
                'image' => 'card/LEVdX5ZfGWfENMsuFnt9Q4SLOLXbTmeKU4jx14u4.png',
                'desc' => '{"en":"The meaning of this card depends on the context.","ru":"Значение этой карты зависит от контекста."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-15 17:11:37',
                'updated_at' => '2022-11-25 01:15:53',
            ),
            78 => 
            array (
                'id' => 61,
                'name' => '{"en":"Green Anaconda"}',
                'code' => NULL,
                'scope_id' => 66,
                'image' => 'card/oKiREBYYEHCZ5beS68QzOn8IDgLyMKYPrYS9UKIv.jpg',
                'desc' => '{"en":"One of the largest snakes in the world, the green anaconda can reach impressive proportions — over 9 meters in length,  and more than 250 kg! Unlike many animals, female anacondas are considerably larger than their male counterparts. Green anacondas are dark olive-brown with large alternating black spots running down their backs and smaller oval spots with yellow centers along their sides. Their eyes and noses are perched on top of their large heads, allowing them to breathe and see their prey even when submerged in water. Green anacondas are members of the boa family and are non-venomous snakes. They use their teeth and powerful jaws to hold onto their prey while their extremely muscular bodies wrap around their catches to suffocate them or drag them underwater."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-13 02:21:46',
                'updated_at' => '2022-11-23 03:39:05',
            ),
            79 => 
            array (
                'id' => 53,
                'name' => '{"en":"Capybara"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/VwGYfuAC7xH2uza8v6MM0HUFqrHXi26e4gCnaT4Y.png',
                'desc' => '{"en":"Capybaras are the largest rodents on earth. They have a heavy, barrel-shaped body that sits on relatively squat legs, shorter in the front than the back. Their brown fur is coarse and sparse enough to reveal the grey skin beneath it.\\r\\n\\r\\nFeeding mostly in the afternoon, and on and off at night, capybaras tend to doze in the morning. They take short naps throughout the day while other members of their group stand guard.\\r\\n\\r\\nThey are herbivores and eat the vegetation that lines water sources and other aquatic plants. They also eat their own poop, which contains beneficial bacteria that helps their stomach to break down the fiber from the grass. During the dry season or in drought conditions, capybaras will also eat grains, melons, reeds and squashes."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 03:22:02',
                'updated_at' => '2022-11-23 03:43:25',
            ),
            80 => 
            array (
                'id' => 91,
                'name' => '{"en":"Moon","ru":"Месяц"}',
                'code' => NULL,
                'scope_id' => 57,
                'image' => 'card/uqLHnLCHHhqTSAzyxnxTJHEGDpT69RnSxF2xDm76.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-25 02:27:59',
                'updated_at' => '2022-11-25 04:16:19',
            ),
            81 => 
            array (
                'id' => 54,
                'name' => '{"en":"Mountain Gorilla"}',
                'code' => NULL,
                'scope_id' => 19,
                'image' => 'card/Lfxen3X1s72bqeYtLAPTICSAeMvBpDEfmf3hPzjN.jpg',
                'desc' => '{"en":"Mountain gorillas are the largest living primates on earth! They can move on their two feet, on all four of their limbs, and can also climb trees and even swing from branches. Mountain gorillas, along with chimpanzees, orangutans, and bonobos, are the closest living relatives of humans, with mountain gorillas having the most developed brain of the four.\\r\\n\\r\\nMountain gorillas live in groups of roughly 30, with one dominant, male troop leader called a ‘silverback’ for the silver tint in his coat. The dominant silverback is in charge of coordinating when the troop eats, rests, and moves around the group’s home range, and the rest of the group is organized in a complex, evolved social order that points to the mountain gorilla’s extraordinary intelligence.\\r\\n\\r\\nMountain gorillas are primarily herbivores and they eat large portions of over 100 different kinds of plants. They do not drink much water because they get most of their needed hydration from their constant consumption of plants."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-12 01:35:45',
                'updated_at' => '2022-11-23 03:42:06',
            ),
            82 => 
            array (
                'id' => 88,
                'name' => '{"en":"Gate","ru":"Ворота"}',
                'code' => NULL,
                'scope_id' => 90,
                'image' => 'card/zy81J8ZRUQaMxEq5pb6Al6Uw2kCIDHN6LerRownF.png',
                'desc' => '{"en":"The Place in front of the Gate. Where the Gate leads depends on the context of the game. Often certain conditions must be met to be able to pass through this Gate.","ru":"Место перед Воротами. Куда ведут Ворота, зависит от контекста игры. Часто для того, чтобы пройти через эти Ворота, необходимо выполнить определенные требования."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 21:02:15',
                'updated_at' => '2022-11-25 04:19:28',
            ),
            83 => 
            array (
                'id' => 44,
                'name' => '{"en":"Shiinhaku","ru":"Шиинхаку"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/mQ1yB3FecgWqaaohds3HXLR70asIWz33e81Ww7Xr.jpg',
                'desc' => '{"en":"From time immemorial, the various tribes of the Rainforest have legends about this insidious and evil spirit.","ru":"С незапамятных времен у различных племен Тропического Леса ходят легенды об этом коварном и злобном духе."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:34:07',
                'updated_at' => '2022-11-23 03:56:17',
            ),
            84 => 
            array (
                'id' => 79,
                'name' => '{"en":"Skill","ru":"Навык"}',
                'code' => NULL,
                'scope_id' => 16,
                'image' => 'card/KjUaRvY8p8Fv7awBHqCFKc12uD77zGmKkf8fcijU.png',
                'desc' => '{"en":"Skills are the ability of a character to do something. The better the skill, the more successfully and efficiently he can perform this action.\\r\\n\\r\\nTIPS: Use as a character deck scope for all his skills.","ru":"Навыки — это способность персонажа делать что-либо. Чем лучше навык, тем успешнее и эффективнее он сможет выполнить связанные с этим навыком действия.\\r\\n\\r\\nПОДСКАЗКИ: Используй в качестве сферы для колоды всех умений персонажа."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:48:50',
                'updated_at' => '2022-11-23 19:23:58',
            ),
            85 => 
            array (
                'id' => 83,
                'name' => '{"en":"Weapon","ru":"Оружие"}',
                'code' => NULL,
                'scope_id' => 6,
                'image' => 'card/qoBl8tq3XdYJFZ38nTLqivvkTPwxFyMBDScit09C.png',
                'desc' => '{"en":"Weapons are one of the most valuable and formidable tools invented by man in ancient times. Since then, innumerable kinds and types of weapons have been invented and tested. One way or another, all types of weapons are united by one of the main properties - harming your enemy or prey.","ru":"Оружие - один из ценных и грозных инструментов, изобретенных человеком уже в глубокой древности. С тех пор были придуманы и опробованы неисчислимые виды и типы оружия. Так или иначе, все виды оружия объединяет одно из главных свойств - нанесение вреда своему врагу или добыче."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 03:07:32',
                'updated_at' => '2022-11-23 19:00:28',
            ),
            86 => 
            array (
                'id' => 6,
                'name' => '{"en":"Item","ru":"Предмет"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/8fgEP6sc7EEKyUZ7nDvM0jhNXASJR5nqWhssOuSn.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:57:58',
                'updated_at' => '2022-11-25 04:28:48',
            ),
            87 => 
            array (
                'id' => 19,
                'name' => '{"en":"Animal","ru":"Животное"}',
                'code' => NULL,
                'scope_id' => 5,
                'image' => 'card/DBFyeFFIXX3Dsif5yDNA3dNNgGt3385hx4LVvW7N.png',
                'desc' => '{"en":"This world is replete with an unimaginable variety of animals."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:13:44',
                'updated_at' => '2022-11-23 02:43:40',
            ),
            88 => 
            array (
                'id' => 80,
                'name' => '{"en":"Survival","ru":"Выживание"}',
                'code' => NULL,
                'scope_id' => 79,
                'image' => 'card/QFL4GNKTOOCHxKRVCprP5jK9u4KfdyQLf1lr6iFp.png',
                'desc' => '{"ru":"Даже в привычном окружении нужно знать как выживать, не говоря уже о том, что в незнакомых диких землях этот навык жизненно необходим буквально как воздух. Навык этот довольно обширен и многогранен, но в первую очередь он дает ключевые знания и опыт о том, как защитить себя от всяческой живности и погодных условий, с которыми можно столкнуться, а также как раздобыть себе годную пищу и воду.\\r\\n\\r\\nЭтот навык имеет специализации для каждого биома, в которых он применяется. Чем больше персонаж  практикует выживание в том, или ином биоме, тем больше растет данная специализация и весь навык в целом.","en":"Even in a familiar environment, you need to know how to survive, not to mention the fact that in an unfamiliar Wilderness this skill is literally as vital as air. This skill is quite extensive and multifaceted, but primarily it provides key knowledge and experience on how to protect yourself from all living creatures and weather conditions that you may encounter, as well as how to get yourself good food and water.\\r\\n\\r\\nThis skill has specializations for each Wilderness biome in which it is used. The more a character practices survival in a particular biome, the more this specialization and the skill as a whole grows."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-16 02:54:14',
                'updated_at' => '2022-11-23 18:34:14',
            ),
            89 => 
            array (
                'id' => 55,
                'name' => '{"en":"Titu","ru":"Титу"}',
                'code' => NULL,
                'scope_id' => 37,
                'image' => 'card/iAp4X50I2pQFwAbFyzLjAPZD3520fhnJBJH5Y7lu.jpg',
                'desc' => '{"en":"The boy from the forest tribe. Originally from the small settlement of Lanza Piya. Raised by parents and other residents of the settlement.\\r\\nHas a younger sister.\\r\\nSmart. Leader among peers.","ru":"Мальчик из лесного племени. Родом из небольшого поселения Ланза Пийя. Воспитан родителями и другими жителями поселения. Имеет младшую сестру. Умен и сообразителен. Лидер среди сверстников."}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:27:58',
                'updated_at' => '2022-11-21 19:24:51',
            ),
            90 => 
            array (
                'id' => 36,
                'name' => '{"en":"Lanza Piya","ru":"Ланза Пийя"}',
                'code' => NULL,
                'scope_id' => 15,
                'image' => 'card/knuT9gJ3iMbWNL4kKWV2mkET57hwywP0Xb42y9EC.jpg',
                'desc' => '{"ru":null}',
                'is_public' => false,
                'owner_id' => 1,
                'created_at' => '2022-11-10 14:31:06',
                'updated_at' => '2022-12-02 02:55:06',
            ),
            91 => 
            array (
                'id' => 37,
                'name' => '{"en":"Hero","ru":"Герой"}',
                'code' => 'hero',
                'scope_id' => 16,
                'image' => 'card/ZUz1OYVtqZJqq3eaGNVD0JdP5IGO5k85cQS6KWvX.png',
                'desc' => '{"ru":"Герой - это любой персонаж, действия которого определяются игроками, а не мастером игры. Это главный персонаж всей игры.","en":"A hero is any character whose actions are determined by the players and not by the gamemaster. This is the main character of the whole game."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-10 23:33:23',
                'updated_at' => '2022-12-04 07:05:19',
            ),
            92 => 
            array (
                'id' => 87,
                'name' => '{"en":"Area","ru":"Локация"}',
                'code' => 'area',
                'scope_id' => 4,
                'image' => 'card/w1MyZg4UpH9O6IB4h6qrFJiietI9AI1NBy7q3cO6.png',
                'desc' => '{"en":"An Area describes the geographical features of a particular Place in the game world.\\r\\n\\r\\nThere are the following types of Areas:\\r\\n- Mountain\\r\\n- River\\r\\n- Lake\\r\\n- etc.\\r\\n\\r\\nHINTS:\\r\\n- Use as a scope for the Hero\'s deck to indicate his current Area.\\r\\n- Use as a scope for a Creature\'s deck to specify the Areas in which that Creature may be found.","ru":"Локация характеризует географические особенности конкретного Места игрового мира.\\r\\n\\r\\nРазличают следующие виды Локаций:\\r\\n- Гора\\r\\n- Река\\r\\n- Озеро\\r\\n- и другие\\r\\n\\r\\nПОДСКАЗКИ:\\r\\n- Используй как сферу для колоды Героя, чтобы указать его текущую Локацию.\\r\\n- Используй как сферу для колоды Существа, чтобы указать Локации, в которых это Существо может быть обнаружено."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-24 19:14:00',
                'updated_at' => '2022-12-04 07:06:08',
            ),
            93 => 
            array (
                'id' => 97,
                'name' => '{"en":"Dome","ru":"Мир"}',
                'code' => 'dome',
                'scope_id' => 4,
                'image' => 'card/B4NfU3toiHggUxWg7S1K39ElNfirBJkFuI65zOR1.png',
                'desc' => '{"ru":null}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-12-04 07:22:33',
                'updated_at' => '2022-12-04 20:30:19',
            ),
            94 => 
            array (
                'id' => 4,
                'name' => '{"ru":"Место","en":"Space"}',
                'code' => NULL,
                'scope_id' => NULL,
                'image' => 'card/UMREeIQTfykvx42Qw49CwLIUFGFgfU2a0zvhyfHT.png',
                'desc' => '{"en":"This is a space of the game world, with its own special properties and characteristics. Places are differentiated by geographical features, natural Biomes, and by the characteristics of the Folk who inhabit the place.\\r\\n\\r\\nHINTS:\\r\\n- Use as a scope for a hero to indicate its current location.\\r\\n- Use as a scope for creatures and items to indicate places where that creature or item can be found.","ru":"Место - это пространство игрового мира, со своими особыми свойствами и характеристиками. Места различаются по географическим особенностям, по природным Биомам, а также по особенностям Народа, населяющего это место.\\r\\n\\r\\nПОДСКАЗКИ:\\r\\n- Используйте как сферу для героя, чтобы указать его текущее местоположение.\\r\\n- Используйте как сферу для существ и предметов, чтобы указать места, в которых это существо или предмет может быть обнаружено."}',
                'is_public' => true,
                'owner_id' => 1,
                'created_at' => '2022-11-08 02:56:32',
                'updated_at' => '2022-12-04 18:50:16',
            ),
        ));
        
        
    }
}